### ISSUE TITLE
plz explain this line properly

### ISSUE THREAD

**Issue by 23BCA305** [vtcbca/internal-exam-23BCA305#2]
program no.2

I Create emp table and insert 8 records. 
I Print only those records where salary > 10000.

but how to do i write the data in salary.csv file

**Comment by 23bca287** [comment]
i have no idea

**Comment by 23BCA309** [comment]
first import csv file an then make a writer cursor and then put the variable in the csv.readlines(varuable_name)in which  you stored data

**Comment by 23BCA305** [comment]
thank you for suggestion
