### ISSUE TITLE
database locked in python

### ISSUE THREAD

**Issue by 23BCA305** [vtcbca/internal-exam-23BCA305#4]
please somebody help

![Annotation 2024-09-20 105039](https://github.com/user-attachments/assets/645f015d-5b86-4e18-b0bf-7a8df95b50c1)

**Comment by 23bca300** [comment]
> please somebody help
> 
> ![Annotation 2024-09-20 105039](https://private-user-images.githubusercontent.com/177290875/369269170-645f015d-5b86-4e18-b0bf-7a8df95b50c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTAwNDEsIm5iZiI6MTcyNjgwOTc0MSwicGF0aCI6Ii8xNzcyOTA4NzUvMzY5MjY5MTcwLTY0NWYwMTVkLTViODYtNGUxOC1iMGJmLTdhOGRmOTViNTBjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwNTIyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDc3MjlmOWU3NTcwOGJiZTQ3M2FlMTIyMjRkMTc5ZWJmZDVjOTFhZTY2MDZmZTcyMmE5ZTIyNDkzNTFhODY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gm2jrlz08m75P_zb4ZpdJgz5a05ez9gAOSBM_u-zlPI)

change database name

**Comment by 23BCA309** [comment]
drop the table and then run all cells again

**Comment by 23BCA305** [comment]
@23bca300 

okay i will change database name
